name: BackendCI

on:
  push:
    paths:
      - 'HotelManagerBackend/**'
  pull_request:
    paths:
      - 'HotelManagerBackend/**'

jobs:
  build-spring-boot:
      runs-on: ubuntu-latest
      steps:
      - name: Chekcout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Ensure mavenwrapper
        run: chmod +x mvnw
        working-directory: HotelManagerBackend
      - name: Build and test
        run: mvnw clean package
        working-directory: HotelManagerBackend
