name: BackendCI

on:
  push:
    paths:
      - 'HotelManagerBackend/**'
  pull_request:
    paths:
      - 'HotelManagerBackend/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    
      - name: Chekcout repo
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'
          
      - name: Build with Maven
        run: mvn clean install -B
        working-directory: HotelManagerBackend
        
      - name: Run tests
        run: mv test
