name: FrontendCI

on:
  push:
    paths:
      - 'HotelManagerFrontend/**'
  pull_request:
    paths:
      - 'HotelManagerFrontend/**'

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
      working-directory: ./HotelManagerFrontend
    - name: run tests
      run: npm test
      working-directory: ./HotelManagerFrontend
